```{r}
#loading data
library(readr)
library(dplyr)
GSE214992 <- read_tsv("/Users/efraimshine/Desktop/rna_seq/GSE214992_deseq2_lclc_vs_high/GSE214992_raw_counts_GRCh38.p13_NCBI.tsv")
Human.GRCh38.p13.annot <- read_tsv("/Users/efraimshine/Desktop/rna_seq/GSE214992_deseq2_lclc_vs_high/Human.GRCh38.p13.annot (1).tsv")
GSE214992
Human.GRCh38.p13.annot <- Human.GRCh38.p13.annot %>% dplyr::select(GeneID,Symbol)
cols_to_select <- c("GeneID",
  "GSM6619719", "GSM6619720", "GSM6619721", "GSM6619722",
  "GSM6619723", "GSM6619724", "GSM6619725", "GSM6619726",
  "GSM6619727", "GSM6619728", "GSM6619729", "GSM6619730",
  "GSM6619731", "GSM6619732", "GSM6619733", "GSM6619734"
)

# cols_to_select_sub <- c("GeneID","GSM6619725","GSM6619727","GSM6619724","GSM6619722","GSM6619719","GSM6619720","GSM6619730","GSM6619734")
cols_to_select_sub <- c("GeneID","GSM6619725","GSM6619724","GSM6619722","GSM6619720","GSM6619730","GSM6619734")

GSE214992_cell_lines <- GSE214992 %>% dplyr::select(all_of(cols_to_select_sub))
GSE214992_cell_lines

GSE214992_annotation_merge <- merge(GSE214992_cell_lines,Human.GRCh38.p13.annot)
GSE214992_annotation_merge

```
```{r}
#prepare data for analysis
GSE214992_annotation_merge_for_deseq2 <- GSE214992_annotation_merge %>% dplyr::select(-GeneID) %>% distinct(Symbol, .keep_all = TRUE)
rownames(GSE214992_annotation_merge_for_deseq2) <- GSE214992_annotation_merge_for_deseq2$Symbol
GSE214992_annotation_merge_for_deseq2$Symbol <- NULL
GSE214992_annotation_merge_for_deseq2


#meta data for analysis
# GSE214992_metadata <- data.frame(cell_type = c(
#   "KO", "KO", "KO", "KO",
#   "KO", "KO", "KO", "KO",
#   "WT", "WT", "WT", "WT",
#   "WT", "WT", "WT", "WT"
# ))
GSE214992_metadata <- data.frame(cell_type = c(
  "KO", "KO",  "KO", "WT", "WT", "WT"
))
rownames(GSE214992_metadata) <- colnames(GSE214992_annotation_merge_for_deseq2)
GSE214992_metadata$cell_type <- as.factor(GSE214992_metadata$cell_type)
GSE214992_metadata
```
```{r}
# run deseq2 for vikash experiments cell lines
library("DESeq2")
dds <- DESeqDataSetFromMatrix(countData = GSE214992_annotation_merge_for_deseq2,
                              colData = GSE214992_metadata,
                              design = ~  cell_type)
dds
dds$cell_type <- relevel(dds$cell_type, ref = "WT")
```

```{r}
dds <- DESeq(dds)
res <- results(dds)
res
```

```{r}
summary(res)
resultsNames(dds)
plotMA(res, ylim=c(-2,2))
```
```{r}
resLFC <- lfcShrink(dds, coef="cell_type_KO_vs_WT", type="apeglm")
resLFC
plotMA(resLFC, ylim=c(-2,2))
```
```{r}
gene_counts_plot <- plotCounts(dds, gene="G6PD", intgroup="cell_type", returnData=TRUE)
gene_counts_plot
plotCounts(dds, gene="G6PD", intgroup="cell_type")
```

```{r}
# clustering
library(clusterProfiler)
library(org.Hs.eg.db)
library(AnnotationDbi)
```
```{r}
sigs_GO <- na.omit(res)
sigs_GO
sigs_GO <- sigs_GO[sigs_GO$padj < 0.05 & sigs_GO$baseMean > 50,]
#sigs_GO <- sigs_GO[sigs_GO$padj < 0.05,]
sigs_GO
genes_to_test_GO <- rownames(sigs_GO[sigs_GO$log2FoldChange > 0.5,])
#genes_to_test_GO <- sub(".*\\.([^\\.]+)\\.$", "\\1", genes_to_test_GO)
length(genes_to_test_GO)
#genes_to_test_GO

GO_results <- enrichGO(gene = genes_to_test_GO, OrgDb = "org.Hs.eg.db", keyType = "SYMBOL", ont = "BP")
path_df_enrich <- as.data.frame(GO_results)
```

```{r}
path_df_enrich
```
```{r}
res_for_gsea <- res[res$baseMean > 50,] 
res_for_gsea <- res_for_gsea[order(-res_for_gsea$log2FoldChange),]
res_for_gsea 

genes_for_gsea <- res_for_gsea$log2FoldChange

names(genes_for_gsea) <- rownames(res_for_gsea)

#names(genes_for_gsea) <- sub(".*\\.([^\\.]+)\\.$", "\\1", rownames(res_for_gsea))
#genes_for_gsea


gsea_res <- gseGO(genes_for_gsea,
             ont = "BP",
             keyType = "SYMBOL",
             OrgDb = "org.Hs.eg.db",
             eps = 1e-300)
```
```{r}
gsea_results_df <- gsea_res %>% as.data.frame()
gsea_results_df
lipid_pathways <- c("lipid catabolic process","regulation of lipid catabolic process","cellular lipid catabolic process","regulation of fatty acid transport","lipid storage")
pathway_name <- "fatty acid beta-oxidation"

gsea_result_pathway_df <- gsea_results_df %>% filter(Description == pathway_name)
gsea_result_pathway_df
pathway_id <- gsea_result_pathway_df[1,1] 
pathway_id
fit_gsea <- gseaplot(gsea_res, geneSetID = pathway_id,title = pathway_name)
fit_gsea
```

