```{r}
library(dplyr)
# explore g6pd expression across celll lines
cell_lines_g6pd_expression <- read.csv("/Users/efraimshine/Desktop/rna_seq/cell_lines/G6PD Expression Public 24Q4.csv")
cell_lines_g6pd_expression_non_cancer <- cell_lines_g6pd_expression %>% filter(Lineage.Subtype == "Non-Cancerous")
cell_lines_g6pd_expression_cancer_only <- cell_lines_g6pd_expression %>% filter(Lineage.Subtype != "Non-Cancerous")
cell_lines_g6pd_expression
cell_lines_g6pd_expression_non_cancer
cell_lines_g6pd_expression_cancer_only
hist(cell_lines_g6pd_expression$Expression.Public.24Q4)
hist(cell_lines_g6pd_expression_non_cancer$Expression.Public.24Q4)
hist(cell_lines_g6pd_expression_cancer_only$Expression.Public.24Q4)
```

```{r}
# z score normalization
cell_lines_g6pd_expression$z_score <- scale(cell_lines_g6pd_expression$Expression.Public.24Q4)
cell_lines_g6pd_expression
hist(cell_lines_g6pd_expression$z_score)
```

```{r}
low_zscore <- cell_lines_g6pd_expression %>% filter(z_score < -1.67 & Lineage == "Lung")
cell_lines_g6pd_expression %>% filter(Cell.Line.Name ==  "LCLC103H")
cell_lines_g6pd_expression %>% filter(Cell.Line.Name ==  "SW48")
lung <- cell_lines_g6pd_expression %>% filter(Lineage == "Lung")
lung
```
```{r}
hist(lung$Expression.Public.24Q4)
hist(lung$z_score)
lung %>% filter(z_score < -1.67)
lung %>% filter(z_score > 1.67)
lung$z_lung <- scale(lung$Expression.Public.24Q4)
hist(lung$z_lung)
lung %>% filter(z_lung < -1.67)
```
```{r}
# annotations
read_counts_depmap <- read.csv("/Users/efraimshine/Desktop/rna_seq/cell_lines/OmicsExpressionGenesExpectedCountProfile.csv")

```

```{r}
model_depmap <- read.csv("/Users/efraimshine/Desktop/rna_seq/cell_lines/Model.csv")
omics_profile_depmap <- read.csv("/Users/efraimshine/Desktop/rna_seq/cell_lines/OmicsProfiles.csv")
read_counts_depmap
model_depmap
omics_profile_depmap


```
```{r}
# Load dplyr for data manipulation
library(dplyr)

# Perform a left join to add ModelID from omics_profile_depmap to read_counts_depmap
# read_counts_depmap_with_modelID <- read_counts_depmap %>%
#   left_join(omics_profile_depmap, by = c("X" = "ProfileID")) %>%
#   relocate(ModelID, .before = X)  # Move ModelID to the first column

# View the updated dataframe


```
```{r}
read_counts_depmap_with_modelID
```

```{r}
read_counts_depmap[is.na(read_counts_depmap$ModelID), ]
non_unique_values <- unique(read_counts_depmap$ModelID[duplicated(read_counts_depmap$ModelID)])
non_unique_values

library(dplyr)

# Get rows with non-unique values in column 'ID'
non_unique_rows <- read_counts_depmap_with_modelID %>%
  group_by(ModelID) %>%
  filter(n() > 1) %>%
  ungroup() %>% arrange(ModelID)

# Print result
print(non_unique_rows)

model_depmap %>% filter(ModelID %in% non_unique_rows$ModelID)
omics_profile_depmap %>% filter(ModelID %in% non_unique_rows$ModelID & Datatype == "rna") %>% arrange(ModelID)
omics_profile_depmap %>% filter(ModelID %in% read_counts_depmap_with_modelID$ModelID & Datatype == "rna" & Stranded == "True") %>% arrange(ModelID)
```
```{r}
omics_profile_depmap %>% filter(Stranded == "False")
```
```{r}
#prepare rna data for analysis
unique_read_counts_depmap_transposed <-  read_counts_depmap_with_modelID %>% distinct(ModelID, .keep_all = TRUE) %>% select(-X) %>% t() %>% as.data.frame() 
colnames(unique_read_counts_depmap_transposed) <- unique_read_counts_depmap_transposed[1, ]
 

```
```{r}
ยง <- unique_read_counts_depmap_transposed[-1, ] 
unique_read_counts_depmap_transposed

```
```{r}

library(dplyr)

# Correct approach


get_df_for_analysis_samples <- function(gene_compromized_samples_vector, control_samples_vector, count_rna_df){
  df_filtered_compromized <- count_rna_df %>% select(all_of(colnames(count_rna_df)[colnames(count_rna_df) %in% gene_compromized_samples_vector]))
  df_filtered_control <- count_rna_df %>% select(all_of(colnames(count_rna_df)[colnames(count_rna_df) %in% control_samples_vector]))
  
}
```
```{r}
colnames(unique_read_counts_depmap_transposed) %in% lung$Depmap.ID
```

```{r}
library(dplyr)

# analysis for cell lines from experiment
model_for_exoriment_cells <- model_depmap %>% filter(StrippedCellLineName %in% c("A549", "AGS","NCIN87","PATU8988T","IGR1","LCLC103H"))
model_for_exoriment_cells

read_counts_for_exoriment_cells <- unique_read_counts_depmap_transposed %>% select(all_of(model_for_exoriment_cells$ModelID))


experimental_cells_metadata <- data.frame(g6pd_status = c("low", "normal","low","normal","normal","low"))
rownames(experimental_cells_metadata) <- colnames(read_counts_for_exoriment_cells)
experimental_cells_metadata$g6pd_status <- as.factor(experimental_cells_metadata$g6pd_status)

read_counts_for_exoriment_cells_int <- read_counts_for_exoriment_cells %>% mutate_all(as.integer)
#read_counts_for_exoriment_cells_int <- read_counts_for_exoriment_cells_int %>% mutate_all(~ replace(., is.na(.), 0))
experimental_cells_metadata
summary(read_counts_for_exoriment_cells)

read_counts_for_exoriment_cells_int %>% filter(is.na(`ACH-000023`))
read_counts_for_exoriment_cells %>% filter(row.names(read_counts_for_exoriment_cells) == "SharedToDbgap")
summary(read_counts_for_exoriment_cells_int)

```
```{r}
# run deseq2 for vikash experiments cell lines
library("DESeq2")
dds <- DESeqDataSetFromMatrix(countData = read_counts_for_exoriment_cells_int,
                              colData = experimental_cells_metadata,
                              design = ~ g6pd_status)
dds

```

