```{r}
gdsc_1_ttest_df <- read.csv("C:\\Users\\sarameirab\\Desktop\\ai_agent_lab_data\\GDSC\\gdsc1_ttest_with_drug_annotation.csv")
gdsc_1_ttest_df
#depmap_ttest_df <- read.csv("C:\\Users\\sarameirab\\Desktop\\ai_agent_lab_data\\depmap\\AllGenesAllDrugLofTtest.csv")
depmap_ttest_df <- read.csv("C:\\Users\\sarameirab\\Desktop\\ai_agent_lab_data\\depmap\\all_genes_all_drugs_ttest_all results.csv")
depmap_ttest_df
```
```{r}
#depmap_ttest_df$BROAD_ID <- sub(".*BRD:([^\\-]+\\-[^\\-]+).*", "BRD-\\1", depmap_ttest_df$drug)
depmap_ttest_df$BROAD_ID <- sub(".*BRD:([^-]+-[^-]+).*", "\\1",depmap_ttest_df$drug)
depmap_ttest_df
```
```{r}
library(tidyr)
gdsc_1_ttest_df_duplicated <- gdsc_1_ttest_df %>%
  separate_rows(BROAD_ID, sep = ",")
gdsc_1_ttest_df_duplicated
```
```{r}
library(dplyr)
# Step 1: Filter out rows with empty 'BROAD_ID'
depmap_ttest_df_filtered <- depmap_ttest_df %>%
  filter(!is.na(BROAD_ID) & BROAD_ID != "")

gdsc_1_ttest_df_duplicated_filtered <- gdsc_1_ttest_df_duplicated %>%
  filter(!is.na(BROAD_ID) & BROAD_ID != "")

# Step 2: Add 'depmap' prefix to columns in depmap_ttest_df
names(depmap_ttest_df_filtered) <- paste("depmap", names(depmap_ttest_df_filtered), sep = "_")
names(depmap_ttest_df_filtered)[names(depmap_ttest_df_filtered) %in% c("depmap_mutation", "depmap_BROAD_ID")] <- c("mutation", "BROAD_ID")

# Add 'gdsc1' prefix to columns in gdsc_1_ttest_df_duplicated
names(gdsc_1_ttest_df_duplicated_filtered) <- paste("gdsc1", names(gdsc_1_ttest_df_duplicated_filtered), sep = "_")
names(gdsc_1_ttest_df_duplicated_filtered)[names(gdsc_1_ttest_df_duplicated_filtered) %in% c("gdsc1_mutation", "gdsc1_BROAD_ID")] <- c("mutation", "BROAD_ID")

# Step 3: Perform an inner join on 'mutation' and 'BROAD_ID'
merged_df <- inner_join(depmap_ttest_df_filtered, gdsc_1_ttest_df_duplicated_filtered, by = c("mutation", "BROAD_ID"))


```

```{r}

merged_df$depmap_effect_size <- merged_df$depmap_no_lof_mean - merged_df$depmap_lof_mean
merged_df
```



```{r}
merged_df_filtered_by_pvalue <- merged_df %>%
  filter(gdsc1_p_value <= 0.01, depmap_p_value <= 0.01)
#merged_df_filtered_by_pvalue$depmap_effect_size <- merged_df_filtered_by_pvalue$depmap_no_lof_mean - merged_df_filtered_by_pvalue$depmap_lof_mean
merged_df_filtered_by_pvalue
```

```{r}
merged_df_filtered_by_pvalue %>% filter(gdsc1_effct_size >1 & depmap_effect_size > 1)

#View(merged_df_filtered_by_pvalue)
#write.csv(merged_df_filtered_by_pvalue, "C:\\Users\\sarameirab\\Desktop\\ai_agent_lab_data\\GDSC\\top_hits_merge_gdsc1_prism_ttests.csv",row.names = FALSE)
```
```{r}
merged_df_filtered_by_effect_size <- merged_df %>% filter(gdsc1_effct_size >1 & depmap_effect_size > 1)
merged_df_filtered_by_effect_size
```




```{r}
merged_df
plot(merged_df$gdsc1_effct_size,merged_df$depmap_effect_size,main = "GDSC1 effect size vs Prism effect size", xlab = "GDSC1 effect size",ylab = "Prism effect size")
#plot(merged_df$depmap_p_value,merged_df$gdsc1_p_value)
plot(merged_df_filtered_by_pvalue$gdsc1_effct_size,merged_df_filtered_by_pvalue$depmap_effect_size,main = "GDSC1 effect size vs Prism effect size pvalue < 0.01", xlab = "GDSC1 effect size",ylab = "Prism effect size")
plot(merged_df_filtered_by_pvalue$gdsc1_effct_size,merged_df_filtered_by_pvalue$depmap_effect_size,main = "GDSC1 effect size vs Prism effect size", xlab = "GDSC1 effect size",ylab = "Prism effect size")
cor(merged_df_filtered_by_pvalue$gdsc1_effct_size, merged_df_filtered_by_pvalue$depmap_effect_size, use = "complete.obs", method = "pearson")
cor.test(merged_df_filtered_by_pvalue$gdsc1_effct_size, merged_df_filtered_by_pvalue$depmap_effect_size, method = "pearson")
```
```{r}
hist(merged_df$depmap_effect_size, breaks = 50, main = "Histogram of depmap_effect_size")
hist(merged_df$gdsc1_effct_size, breaks = 50, main = "Histogram of gdsc1_effct_size")

```

```{r}
merged_df_filtered_by_pvalue 
merged_df_filtered_by_pvalue[order(merged_df_filtered_by_pvalue$mutation), ]
merged_df_filtered_by_pvalue[order(merged_df_filtered_by_pvalue$depmap_p_value), ]
order_by_drug_name <- merged_df_filtered_by_pvalue[order(merged_df_filtered_by_pvalue$gdsc1_DRUG_NAME), ] 
merged_df_filtered_by_pvalue[order(-merged_df_filtered_by_pvalue$depmap_lof_count), ]
merged_df_filtered_by_pvalue[order(-merged_df_filtered_by_pvalue$depmap_effect_size), ]

#order_by_drug_name %>% filter(gdsc1_DRUG_NAME == "REFAMETINIB")
#order_by_drug_name %>% filter(gdsc1_DRUG_NAME == "SELUMETINIB")
```
```{r}
merged_df_filtered_by_pvalue %>% filter(gdsc1_effct_size > 2)
```

