

```{r}
source("~/workspace/bioinformatics_analysis/project_code/r_scripts/download_data.R")
gse_190928_path <- download_url("https://drive.google.com/file/d/1Ib4vK8fEpwHDv_sjScb9nksmzaeQ8wTt", type="tsv")
Human.GRCh38.p13.annot_path <- download_url("https://drive.google.com/file/d/1YNV_8jkt9LtUePx2NnvfTjZRY_cGCvVK", type="tsv")
```






```{r}
#loading data
library(readr)
GSE190928 <- read_tsv(gse_190928_path)
Human.GRCh38.p13.annot <- read_tsv(Human.GRCh38.p13.annot_path)
GSE190928
Human.GRCh38.p13.annot
GSE190928_annotation_merge <- merge(GSE190928,Human.GRCh38.p13.annot)
GSE190928_annotation_merge
```
```{r}
#prepare data for analysis
library(dplyr)
GSE190928_counts_for_deseq <- GSE190928_annotation_merge %>% dplyr::select(Symbol,GSM5734411,GSM5734412,GSM5734413,GSM5734414,GSM5734415,GSM5734416) %>% distinct(Symbol, .keep_all = TRUE)
rownames(GSE190928_counts_for_deseq) <- GSE190928_counts_for_deseq$Symbol
GSE190928_counts_for_deseq$Symbol <- NULL
GSE190928_counts_for_deseq


#meta data for analysis
GSE190928_metadata <- data.frame(g6pd_status = c("WT","WT","WT","KD","KD","KD"))
rownames(GSE190928_metadata) <- colnames(GSE190928_counts_for_deseq)
GSE190928_metadata$g6pd_status <- as.factor(GSE190928_metadata$g6pd_status)
GSE190928_metadata
```

```{r}
# run deseq2 for vikash experiments cell lines
library("DESeq2")
dds <- DESeqDataSetFromMatrix(countData = GSE190928_counts_for_deseq,
                              colData = GSE190928_metadata,
                              design = ~  g6pd_status)
dds
dds$g6pd_status <- relevel(dds$g6pd_status, ref = "WT")
```
```{r}
dds <- DESeq(dds)
res <- results(dds)
res
```

```{r}
summary(res)
resultsNames(dds)
plotMA(res, ylim=c(-2,2))

```
```{r}
resLFC <- lfcShrink(dds, coef="g6pd_status_KD_vs_WT", type="apeglm")
resLFC
plotMA(resLFC, ylim=c(-2,2))
```
```{r}
plotDispEsts(dds)
```
```{r}
vsd <- vst(dds,blind = FALSE)
vsd
plotPCA(vsd, intgroup = "g6pd_status")
```

```{r}
# clustering
library(clusterProfiler)
library(org.Hs.eg.db)
library(AnnotationDbi)
library(EnhancedVolcano)
```


```{r}
EnhancedVolcano(res,
    lab = rownames(res),
    x = 'log2FoldChange',
    y = 'pvalue')
```
```{r}
df_res <- as.data.frame(res)
df_res$Symbol <- rownames(df_res)
df_res
df_res %>% filter(Symbol == "ALDH1A3")
```



```{r}
sigs_GO <- na.omit(res)
sigs_GO
sigs_GO <- sigs_GO[sigs_GO$padj < 0.05 & sigs_GO$baseMean > 50,]
#sigs_GO <- sigs_GO[sigs_GO$padj < 0.05,]
sigs_GO
genes_to_test_GO <- rownames(sigs_GO[sigs_GO$log2FoldChange > 0.5,])
#genes_to_test_GO <- sub(".*\\.([^\\.]+)\\.$", "\\1", genes_to_test_GO)
length(genes_to_test_GO)
#genes_to_test_GO
set.seed(1234)
GO_results <- enrichGO(gene = genes_to_test_GO, OrgDb = "org.Hs.eg.db", keyType = "SYMBOL", ont = "BP")
path_df_enrich <- as.data.frame(GO_results)
path_df_enrich


```


```{r}
path_df_enrich


lipid_pathways <- c("lipid catabolic process","regulation of lipid catabolic process","cellular lipid catabolic process","regulation of fatty acid transport","lipid storage")

lipid_pathways_enrich <- GO_results %>% filter(Description %in% lipid_pathways)


fit_KD <- plot(barplot(GO_results, showCategory = 10))
library(clusterProfiler)
library(ggplot2)

# Original plot
fit_KD <- barplot(GO_results, showCategory = 10)

# Add title and change axis labels
fit_KD +
  ggtitle("Top Enriched GO Terms in Upregulated genes") +
  xlab("Number of Genes") +
  ylab("GO Term") +
  theme_bw() +  # optional cleaner look
  theme(
    plot.title = element_text(hjust = 1, size = 14, face = "bold"),
    axis.title.x = element_text(size = 12),
    axis.title.y = element_text(size = 12)
  )

#png("out.png", res = 250, width = 1400, height = 1800)
#print(fit_KD)
#dev.off()
```
```{r}
#gsea 
res_for_gsea <- res[res$baseMean > 50,] 
res_for_gsea <- res_for_gsea[order(-res_for_gsea$log2FoldChange),]
res_for_gsea 

genes_for_gsea <- res_for_gsea$log2FoldChange

names(genes_for_gsea) <- rownames(res_for_gsea)

#names(genes_for_gsea) <- sub(".*\\.([^\\.]+)\\.$", "\\1", rownames(res_for_gsea))
#genes_for_gsea

set.seed(2345)
gsea_res <- gseGO(genes_for_gsea,
             ont = "BP",
             keyType = "SYMBOL",
             OrgDb = "org.Hs.eg.db",
             eps = 1e-300)
```

```{r}
gsea_results_df <- gsea_res %>% as.data.frame()
gsea_results_df


```
```{r}
lipid_pathways <- c("lipid catabolic process","regulation of lipid catabolic process","cellular lipid catabolic process","regulation of fatty acid transport","lipid storage")
pathway_name <- "glucose metabolic process"

gsea_result_pathway_df <- gsea_results_df %>% filter(Description == pathway_name)
gsea_result_pathway_df
pathway_id <- gsea_result_pathway_df[1,1] 
pathway_id
fit_gsea <- gseaplot(gsea_res, geneSetID = pathway_id,title = pathway_name)
fit_gsea
# png("/Users/efraimshine/Desktop/rna_seq/cell_lines/lipid catabolic process.png", res = 250, width = 1800, height = 1400)
# print(fit_gsea)
# dev.off()

fit_gsea <- gseaplot(gsea_res, geneSetID = pathway_id,title = "fatty acid catabolic process")
fit_gsea
```

```{r}
library(dplyr)
library(ggplot2)

top11 <- gsea_results_df %>% slice(1:11)

ggplot(top11, aes(x = reorder(Description, NES), y = NES, fill = NES)) +
  geom_col() +
  coord_flip() +
  labs(title = "Top 11 Enriched Pathways",
       x = "GO Term",
       y = "Normalized Enrichment Score (NES)") +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
  theme_minimal()

```
```{r}
clusterProfiler::dotplot(gsea_res, showCategory = 11) +
  ggtitle("Top Enriched Pathways from GSEA") +
  
  ylab("GO Term") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, size = 14, face = "bold"))


clusterProfiler::emapplot(gsea_res, showCategory = 11) +
  ggtitle("Enrichment Map of Top Pathways") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, size = 14, face = "bold"))


clusterProfiler::cnetplot(gsea_res, showCategory = 11) +
  ggtitle("Cnet Plot of Top Pathways") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, size = 14, face = "bold"))

clusterProfiler::ridgeplot(gsea_res, showCategory = 11) +
  ggtitle("Ridge Plot of Top Pathways") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, size = 14, face = "bold"))

gseaplot2(gsea_res, geneSetID = pathway_id, title = pathway_name) +
  ggtitle("GSEA Plot for Specific Pathway") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, size = 14, face = "bold"))

barplot(gsea_res, showCategory = 11) +
  ggtitle("Bar Plot of Top Pathways") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, size = 14, face = "bold"))
```
```{r}
library(ggplot2)
library(dplyr)

# Keep top 30
plot_df <- gsea_results_df %>%
  slice_head(n = 11) %>%
  arrange(NES) %>%
  mutate(Description = factor(Description, levels = Description))  # for ordering bars

# Plot
ggplot(plot_df, aes(x = Description, y = NES, fill = p.adjust)) +
  geom_col() +
  scale_fill_gradient(low = "red", high = "blue", name = "Adjusted p-value") +
  coord_flip() +  # Flip for better readability
  theme_minimal(base_size = 17) +
  labs(
    title = "Top Enriched GSEA Pathways",
    x = "GO Pathways",
    y = "Normalized Enrichment Score"
  )
```
```{r}
library(clusterProfiler)
library(enrichplot)

# Choose the pathway you want (use ID, not Description)
pathway_id <- "GO:0016042"  # example: lipid biosynthetic process

gseaplot2(gsea_res, 
          geneSetID = pathway_id, 
          title = gsea_results_df$Description[gsea_results_df$ID == pathway_id])


gseaplot(gsea_res, 
         geneSetID = pathway_id, 
         by = "all",   # can be "runningScore", "preranked", or "all"
         title = gsea_results_df$Description[gsea_results_df$ID == pathway_id])

cnetplot(gsea_res, 
         foldChange = genes_for_gsea, 
         showCategory = 11,    # top category
         categorySize = "pvalue", 
         colorEdge = TRUE)



```

