```{r}
#loading data
library(readr)
library(dplyr)
GSE190928 <- read_tsv("/Users/efraimshine/Desktop/rna_seq/PC3_vs_SCC_GSE187454VSGSE190928/GSE190928_raw_counts_GRCh38.p13_NCBI.tsv")
Human.GRCh38.p13.annot <- read_tsv("/Users/efraimshine/Desktop/rna_seq/PC3_vs_SCC_GSE187454VSGSE190928/Human.GRCh38.p13.annot (1).tsv")
GSE187454 <- read_tsv("/Users/efraimshine/Desktop/rna_seq/PC3_vs_SCC_GSE187454VSGSE190928/GSE187454_raw_counts_GRCh38.p13_NCBI.tsv")
GSE187454_SCC_cell_line <- GSE187454 %>% dplyr::select(GeneID,GSM5668518,GSM5668519,GSM5668520,GSM5668521)
GSE190928
GSE187454
GSE187454_SCC_cell_line
Human.GRCh38.p13.annot
GSE190928_annotation_merge <- merge(GSE190928,Human.GRCh38.p13.annot)
GSE190928_annotation_merge
GSE190928_GSE187454_annotation_merge <- merge(GSE190928_annotation_merge, GSE187454_SCC_cell_line)
GSE190928_GSE187454_annotation_merge
```
```{r}
#prepare data for analysis
GSE190928_GSE187454_counts_for_deseq <- GSE190928_GSE187454_annotation_merge %>% dplyr::select(Symbol,GSM5734411,GSM5734412,GSM5734413,GSM5668518,GSM5668519,GSM5668520,GSM5668521) %>% distinct(Symbol, .keep_all = TRUE)
rownames(GSE190928_GSE187454_counts_for_deseq) <- GSE190928_GSE187454_counts_for_deseq$Symbol
GSE190928_GSE187454_counts_for_deseq$Symbol <- NULL
GSE190928_GSE187454_counts_for_deseq


#meta data for analysis
GSE190928_GSE187454_metadata <- data.frame(cell_type = c("PC3","PC3","PC3","SCC","SCC","SCC","SCC"))
rownames(GSE190928_GSE187454_metadata) <- colnames(GSE190928_GSE187454_counts_for_deseq)
GSE190928_GSE187454_metadata$cell_type <- as.factor(GSE190928_GSE187454_metadata$cell_type)
GSE190928_GSE187454_metadata
```
```{r}
# run deseq2 for vikash experiments cell lines
library("DESeq2")
dds <- DESeqDataSetFromMatrix(countData = GSE190928_GSE187454_counts_for_deseq,
                              colData = GSE190928_GSE187454_metadata,
                              design = ~  cell_type)
dds
dds$cell_type <- relevel(dds$cell_type, ref = "PC3")
```

```{r}
dds <- DESeq(dds)
res <- results(dds)
res
```

```{r}
summary(res)
resultsNames(dds)
plotMA(res, ylim=c(-2,2))
```
```{r}
resLFC <- lfcShrink(dds, coef="cell_type_SCC_vs_PC3", type="apeglm")
resLFC
plotMA(resLFC, ylim=c(-2,2))
```
```{r}
gene_counts_plot <- plotCounts(dds, gene="G6PD", intgroup="cell_type", returnData=TRUE)
gene_counts_plot
plotCounts(dds, gene="G6PD", intgroup="cell_type")
```

```{r}
# clustering
library(clusterProfiler)
library(org.Hs.eg.db)
library(AnnotationDbi)
```
```{r}
sigs_GO <- na.omit(res)
sigs_GO
sigs_GO <- sigs_GO[sigs_GO$padj < 0.05 & sigs_GO$baseMean > 50,]
#sigs_GO <- sigs_GO[sigs_GO$padj < 0.05,]
sigs_GO
genes_to_test_GO <- rownames(sigs_GO[sigs_GO$log2FoldChange < -0.5,])
#genes_to_test_GO <- sub(".*\\.([^\\.]+)\\.$", "\\1", genes_to_test_GO)
length(genes_to_test_GO)
#genes_to_test_GO

GO_results <- enrichGO(gene = genes_to_test_GO, OrgDb = "org.Hs.eg.db", keyType = "SYMBOL", ont = "BP")
path_df_enrich <- as.data.frame(GO_results)
```

```{r}
path_df_enrich
```
```{r}
res_for_gsea <- res[res$baseMean > 50,] 
res_for_gsea <- res_for_gsea[order(-res_for_gsea$log2FoldChange),]
res_for_gsea 

genes_for_gsea <- res_for_gsea$log2FoldChange

names(genes_for_gsea) <- rownames(res_for_gsea)

#names(genes_for_gsea) <- sub(".*\\.([^\\.]+)\\.$", "\\1", rownames(res_for_gsea))
#genes_for_gsea


gsea_res <- gseGO(genes_for_gsea,
             ont = "BP",
             keyType = "SYMBOL",
             OrgDb = "org.Hs.eg.db",
             eps = 1e-300,pvalueCutoff = 1)
```
```{r}
gsea_results_df <- gsea_res %>% as.data.frame()
gsea_results_df
lipid_pathways <- c("lipid catabolic process","regulation of lipid catabolic process","cellular lipid catabolic process","regulation of fatty acid transport","lipid storage")
pathway_name <- "fatty acid beta-oxidation"

gsea_result_pathway_df <- gsea_results_df %>% filter(Description == pathway_name)
gsea_result_pathway_df
pathway_id <- gsea_result_pathway_df[1,1] 
pathway_id
fit_gsea <- gseaplot(gsea_res, geneSetID = pathway_id,title = pathway_name)
fit_gsea
```

