```{r}
#loading data
library(readr)
GSE207499 <- read_tsv("/Users/efraimshine/Desktop/rna_seq/netta_rna_seq/GSE207499_raw_counts_GRCh38.p13_NCBI.tsv")
Human.GRCh38.p13.annot <- read_tsv("/Users/efraimshine/Desktop/rna_seq/netta_rna_seq/Human.GRCh38.p13.annot (2).tsv")
GSE207499 %>% arrange(GeneID)
Human.GRCh38.p13.annot
GSE207499_annotation_merge <- merge(GSE207499,Human.GRCh38.p13.annot)
GSE207499_annotation_merge

GSE207499_for_deseq <- GSE207499_annotation_merge %>% dplyr::select(Symbol,GSM6290621,GSM6290622,GSM6290623,GSM6290624,GSM6290625,GSM6290626,GSM6290627,GSM6290628,GSM6290629)
GSE207499_for_deseq %>% arrange(Symbol)

```
```{r}
#ctr vs KD
GSE207499_for_deseq_KO_CTR <- GSE207499_for_deseq %>% dplyr::select(-GSM6290627,-GSM6290628,-GSM6290629) %>% distinct(Symbol, .keep_all = TRUE)
rownames(GSE207499_for_deseq_KO_CTR) <- GSE207499_for_deseq_KO_CTR$Symbol
GSE207499_for_deseq_KO_CTR$Symbol <- NULL
GSE207499_for_deseq_KO_CTR %>% arrange(rownames(GSE207499_for_deseq_KO_CTR))


# metadata ctr vs KO

GSE207499_Ctr_KO_metadata <- data.frame(SGPL1_status = c("Ctr","Ctr","Ctr","KO","KO","KO"))
rownames(GSE207499_Ctr_KO_metadata) <- colnames(GSE207499_for_deseq_KO_CTR)
GSE207499_Ctr_KO_metadata$SGPL1_status <- as.factor(GSE207499_Ctr_KO_metadata$SGPL1_status)
GSE207499_Ctr_KO_metadata
```
```{r}
# run deseq2 for vikash experiments cell lines
library("DESeq2")
dds <- DESeqDataSetFromMatrix(countData = GSE207499_for_deseq_KO_CTR,
                              colData = GSE207499_Ctr_KO_metadata,
                              design = ~ SGPL1_status)
dds
dds$SGPL1_status <- relevel(dds$SGPL1_status, ref = "Ctr")
```

```{r}
dds <- DESeq(dds)
res <- results(dds)
res
```

```{r}
summary(res)
resultsNames(dds)
plotMA(res, ylim=c(-2,2))

```
```{r}
resLFC <- lfcShrink(dds, coef="SGPL1_status_KO_vs_Ctr", type="apeglm")
resLFC
plotMA(resLFC, ylim=c(-2,2))
```

```{r}
# clustering
library(clusterProfiler)
library(org.Hs.eg.db)
library(AnnotationDbi)
```
```{r}
sigs_GO <- na.omit(res)
sigs_GO
sigs_GO <- sigs_GO[sigs_GO$padj < 0.05 & sigs_GO$baseMean > 50,]
#sigs_GO <- sigs_GO[sigs_GO$padj < 0.05,]
sigs_GO
genes_to_test_GO <- rownames(sigs_GO[abs(sigs_GO$log2FoldChange) > 0.5, ])

#genes_to_test_GO <- sub(".*\\.([^\\.]+)\\.$", "\\1", genes_to_test_GO)
length(genes_to_test_GO)
#genes_to_test_GO

GO_results <- enrichGO(gene = genes_to_test_GO, OrgDb = "org.Hs.eg.db", keyType = "SYMBOL", ont = "BP")
path_df_enrich <- as.data.frame(GO_results)
path_df_enrich
```
```{r}
c("GO:2000124","GO:0071926")
path_df_enrich %>% filter(ID == "GO:2000124")
```


```{r}
write.csv(res, "/Users/efraimshine/Desktop/rna_seq/netta_rna_seq/Deseq2.csv", row.names = TRUE)


```

```{r}
res_for_gsea <- res[res$baseMean > 50,] 
res_for_gsea <- res_for_gsea[order(-res_for_gsea$log2FoldChange),]
res_for_gsea 

genes_for_gsea <- res_for_gsea$log2FoldChange

names(genes_for_gsea) <- rownames(res_for_gsea)

#names(genes_for_gsea) <- sub(".*\\.([^\\.]+)\\.$", "\\1", rownames(res_for_gsea))
#genes_for_gsea


gsea_res <- gseGO(genes_for_gsea,
             ont = "BP",
             keyType = "SYMBOL",
             OrgDb = "org.Hs.eg.db",
             eps = 1e-300,
             pvalueCutoff = 1)

```

```{r}
gsea_res_df <- as.data.frame(gsea_res) 
gsea_res_df
```

