---
title: "TCGA_DESEQ2_propensity_score_matching"
output: html_document
---


```{r}
library("R.utils")
library("dplyr")
library("data.table")
library("readr")
source("~/workspace/bioinformatics_analysis/project_code/r_scripts/download_data.R")
```
```{r}
setwd("~/Desktop/rna_seq/TCGA")

data("XenaData")
write.csv(XenaData, "00_tblXenaHubInfo.csv")

## step 5-a
GeneExpectedCnt_toil = XenaGenerate(subset = XenaHostNames == "toilHub") %>% 
  XenaFilter(filterCohorts = "TCGA TARGET GTEx") %>%
  XenaFilter(filterDatasets = "TcgaTargetGtex_gene_expected_count");
XenaQuery(GeneExpectedCnt_toil) %>%
  XenaDownload(destdir = "./")
samples_gene_expression = fread("TcgaTargetGtex_gene_expected_count.gz");

```
```{r}
samples_availible_in_xena <- colnames(samples_gene_expression)[-1] #first column is gene names

```

```{r}
TCGA_samples_data_path <- download_url("https://drive.google.com/file/d/1ELYxyn6lnF__Pc7YX2NtiitwWCCZNq-n", type="tsv")
#g6pd_deleted_samples_file <-download_url("https://drive.google.com/file/d/1BxjcimPvrUOFOzLLbkwWc0fqyQGOLyju") #deleted samples
g6pd_deleted_and_mutated_samples_file <- download_url("https://drive.google.com/file/d/1eRDm68CTg2e4tUvJrJWWoYaJCPnNJm_v")#deleted and mutated samples together

g6pd_deleted_samples_file <- g6pd_deleted_and_mutated_samples_file
```

```{r}
#preparing TCGA samples information and taking only samples availible in xena servers
TCGA_samples_info <- read_tsv(TCGA_samples_data_path, col_names = TRUE, show_col_types = FALSE)
colnames(TCGA_samples_info) <- gsub("\\s+", "_", colnames(TCGA_samples_info))

#filtering only samples that are available in xena

TCGA_samples_availible_in_xena_info <- TCGA_samples_info %>% filter(Sample_ID %in% samples_availible_in_xena)

TCGA_samples_info <- TCGA_samples_availible_in_xena_info
TCGA_samples_info

```

```{r}
# #preparing deleted samples information
# g6pd_deleted_samples <- read_tsv(g6pd_deleted_samples_file, col_names = TRUE, show_col_types = FALSE)
# # Move current column names into the first row as values
# g6pd_deleted_samples <- rbind(colnames(g6pd_deleted_samples), g6pd_deleted_samples)
# # Fix the column names, starting with "Sample_id"
# colnames(g6pd_deleted_samples) <- c("Sample_id", paste0("V", 2:ncol(g6pd_deleted_samples)))
# g6pd_deleted_samples
# #get clinical information for deleted samples
# g6pd_deleted_samples_info <- TCGA_samples_info %>% 
#   filter(Sample_ID %in% g6pd_deleted_samples$Sample_id)
# 
# 
# g6pd_deleted_samples_info 

```
```{r}
#run only for mutated and deleted samples together
g6pd_deleted_samples <- read_tsv(g6pd_deleted_samples_file, col_names = TRUE, show_col_types = FALSE)
g6pd_deleted_samples
# Fix the column names, starting with "Sample_id"
colnames(g6pd_deleted_samples) <- c("Sample_id", paste0("V", 2:ncol(g6pd_deleted_samples)))
g6pd_deleted_samples
#get clinical information for deleted samples
g6pd_deleted_samples_info <- TCGA_samples_info %>% 
  filter(Sample_ID %in% g6pd_deleted_samples$Sample_id)


g6pd_deleted_samples_info 

```

```{r}
# assinging G6PD_STATUS to TCGA_samples_info
full_clin <- TCGA_samples_info %>%
  mutate(G6PD_STATUS = ifelse(Sample_ID %in% g6pd_deleted_samples_info$Sample_ID, "deleted", "not_deleted")) #%>% select(Sample_ID, G6PD_STATUS, everything())
full_clin

full_clin$American_Joint_Committee_on_Cancer_Tumor_Stage_Code
g6pd_deleted_samples_info$American_Joint_Committee_on_Cancer_Tumor_Stage_Code
```



```{r}
library(MatchIt)
library(dplyr)
library(tidyr)
library(stringr)


full_clin <- full_clin %>%                 # your master table
  dplyr::rename(
    TMB_raw            = `TMB_(nonsynonymous)`,
    AJCC_Tumor_Stage   = American_Joint_Committee_on_Cancer_Tumor_Stage_Code
  ) %>%
  mutate(
    ## --- treatment flag -----------------------------------------------------
    treated = ifelse(G6PD_STATUS == "deleted", 1, 0),
    
    ## --- AGE ----------------------------------------------------------------
    age_missing     = as.integer(is.na(Diagnosis_Age)),
    Diagnosis_Age   = replace_na(Diagnosis_Age,
                                 median(Diagnosis_Age, na.rm = TRUE)),
    
    ## --- SEX (categorical) --------------------------------------------------
    Sex = factor(replace_na(Sex, "Unknown")),
    
    ## --- TMB (numeric, log-scaled) -----------------------------------------
    TMB_missing     = as.integer(is.na(TMB_raw)),
    TMB_ns          = log10(replace_na(TMB_raw,
                                       median(TMB_raw, na.rm = TRUE)) + 1),
    
    ## --- Aneuploidy (numeric) ----------------------------------------------
    Aneuploidy_missing = as.integer(is.na(Aneuploidy_Score)),
    Aneuploidy_Score   = replace_na(Aneuploidy_Score,
                                    median(Aneuploidy_Score, na.rm = TRUE)),
    
    ## --- Race / Ethnicity (categorical) -------------------------------------
    Race_Category       = factor(replace_na(Race_Category, "Unknown")),
    Ethnicity_Category  = factor(replace_na(Ethnicity_Category, "Unknown")),
    
    ## --- Collapse tumour stage (optional) -----------------------------------
    AJCC_stage_collapsed = case_when(
      is.na(AJCC_Tumor_Stage)            ~ "Unknown",            # missing
      AJCC_Tumor_Stage == "TX"           ~ "Unknown",            # stage not assessed
      AJCC_Tumor_Stage == "TIS"          ~ "Low",                # in-situ
      str_detect(AJCC_Tumor_Stage, "^T[0-2]")  ~ "Low",          # T0, T1*, T2*
      str_detect(AJCC_Tumor_Stage, "^T[3-4]")  ~ "High",         # T3*, T4*
      TRUE                                ~ "Unknown"            # any odd leftovers
    )
  )

full_clin
```
```{r}
library(dplyr)

fact_vars <- c("Sex", "Race_Category", "Ethnicity_Category", "AJCC_stage_collapsed")

full_clin %>%
  summarise(across(all_of(fact_vars),
                   ~ n_distinct(.x))) %>%
  pivot_longer(everything(),
               names_to = "variable", values_to = "n_levels")
full_clin

```


```{r}
m.out <- matchit(
  treated ~ Diagnosis_Age + age_missing +
            Sex +
            TMB_ns + TMB_missing +
            Aneuploidy_Score + Aneuploidy_missing +
            AJCC_stage_collapsed +
            Race_Category + Ethnicity_Category,
  data     = full_clin,
  method   = "nearest",
  exact    = ~ TCGA_PanCanAtlas_Cancer_Type_Acronym,   # still within-cancer
  ratio    = 2,
  caliper  = 0.2
)

summary(m.out)        # all |SMD| should now be ≤0.10

```

```{r}
library(cobalt)
love.plot(m.out, binary = "std",)      # bar plot of SMDs
plot(m.out, type = "jitter")          # PS overlap
plot(m.out, type = "hist")

```
```{r}
matched_ids <- match.data(m.out)$Sample_ID
matched_ids
```
```{r}
 propensity_samples_info <- match.data(m.out)
propensity_samples_info
```
```{r}
propensity_score_samples <-   propensity_samples_info %>% filter(G6PD_STATUS == "not_deleted") %>% select(Sample_ID)
propensity_score_samples
propensity_score_deleted <- propensity_samples_info %>% filter(G6PD_STATUS == "deleted") %>% select(Sample_ID)
propensity_score_deleted
```

